image: "hub.ricebook.net/base/centos:onbuild-eru-core-2017.07.21"
variables:
  CITADEL_AUTH_TOKEN: "jq9QkdQMXIsE6x7omemfpFgUd1ql6bAX3ATIH7huKUA9TJU7gLFT663pC0cG8dU9"
  CITADEL_URL: "http://citadel.ricebook.net"
  MIMIRON_URL: "http://mimiron.ricebook.net"
  SSO_URL: "http://sso.ricebook.net"
stages:
  - "build"
  - "core_build"
build_job:
  stage: "build"
  script:
    - "git clone http://gitlab.ricebook.net/platform/core.git $GOPATH/src/gitlab.ricebook.net/platform/core"
    - "git clone http://gitlab.ricebook.net/platform/agent.git $GOPATH/src/gitlab.ricebook.net/platform/agent"
    - "go get -u -v -d github.com/Sirupsen/logrus"
    - "go get -u -v -d github.com/coreos/etcd/client"
    - "go get -u -v -d github.com/deckarep/golang-set"
    - "go get -u -v -d github.com/gin-gonic/gin"
    - "ln -s $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/eru-stats"
    - "go build -ldflags \"$(GO_LDFLAGS)\" -a -tags netgo -installsuffix netgo -o eru-stats"
  artifacts:
    paths:
      - "eru-stats"
    expire_in: "1 week"
core_build_job:
  image: "hub.ricebook.net/base/centos:golang-latest"
  stage: "core_build"
  script:
    - "corecli --debug register"
    - "corecli --debug build --with-artifacts"
    