appname: "eru-stats"
entrypoints:
  api:
    cmd: "eru-stats"
    ports:
      - "6006/tcp"
    restart: "on-failure"
    healthcheck_url: "/ping"
    healthcheck_expected_code: 200
build:
  - "cp eru-stats /usr/bin"
  - "eru-stats --version"
base: "hub.ricebook.net/base/alpine:base-2017.03.14"
subscribers: "@wrfly_;"
volumes:
  - "$PERMDIR/:/etc/eru/"
permitted_users:
  - "cmgs"
  - "fushouguo"