appname: "eru-stats"
entrypoints:
  api:
    cmd: "eru-stats"
    ports:
      - "6006/tcp"
    restart: "on-failure"
    healthcheck_url: "/ping"
    healthcheck_expected_code: 200
build:
  - "eru-stats --version"
base: "hub.ricebook.net/base/alpine:base-2017.03.14"
permitted_users:
  - "cmgs"
  - "fushouguo"
combos:
  test-in-c1:
    cpu: 1
    memory: "64MB"
    podname: "dev"
    entrypoint: "api"
    networks:
      - "release"
    envs: "FOO=bar;"